In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
import kagglehub
# Download latest version
path = kagglehub.dataset_download("wasiqaliyasir/breast-cancer-dataset")

print("Path to dataset files:", path)

100%|██████████| 48.7k/48.7k [00:00<00:00, 2.91MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/wasiqaliyasir/breast-cancer-dataset/versions/1


In [3]:
os.listdir(path)

['Breast_cancer_dataset.csv']

In [4]:
dataset_path=os.path.join(path,'Breast_cancer_dataset.csv')
dataset_path

'/root/.cache/kagglehub/datasets/wasiqaliyasir/breast-cancer-dataset/versions/1/Breast_cancer_dataset.csv'

In [5]:
df=pd.read_csv(dataset_path)
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [6]:
cols=df.columns
cols

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [7]:
mean_attributes=['radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean']
se_attributes=['radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se']
worst_attributes=['radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst']
target_col='diagnosis'


In [9]:
df.drop(['id','Unnamed: 32'],axis=1,inplace=True)

In [10]:
df.isnull().sum()

diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [12]:
X_mean=df[mean_attributes]
y=df[target_col]

In [13]:
df.diagnosis.value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [14]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_mean,y,test_size=0.2,random_state=9)

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [17]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_train,y_train)
y_lr=lr.predict(X_test)


In [18]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_lr))
print(confusion_matrix(y_test,y_lr))
print(classification_report(y_test,y_lr))

0.9385964912280702
[[72  2]
 [ 5 35]]
              precision    recall  f1-score   support

           0       0.94      0.97      0.95        74
           1       0.95      0.88      0.91        40

    accuracy                           0.94       114
   macro avg       0.94      0.92      0.93       114
weighted avg       0.94      0.94      0.94       114



In [19]:
from sklearn.neighbors import KNeighborsClassifier
knn_3=KNeighborsClassifier(n_neighbors=3)
knn_3.fit(X_train,y_train)
y_knn_3=knn_3.predict(X_test)

In [20]:
print(accuracy_score(y_test,y_knn_3))
print(confusion_matrix(y_test,y_knn_3))
print(classification_report(y_test,y_knn_3))

0.956140350877193
[[71  3]
 [ 2 38]]
              precision    recall  f1-score   support

           0       0.97      0.96      0.97        74
           1       0.93      0.95      0.94        40

    accuracy                           0.96       114
   macro avg       0.95      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



In [21]:
knn_5=KNeighborsClassifier(n_neighbors=5)
knn_5.fit(X_train,y_train)
y_knn_5=knn_5.predict(X_test)

In [22]:
print(accuracy_score(y_test,y_knn_5))
print(confusion_matrix(y_test,y_knn_5))

0.9473684210526315
[[71  3]
 [ 3 37]]


In [23]:
from sklearn.svm import SVC
svc_lin=SVC(kernel='linear')
svc_lin.fit(X_train,y_train)
y_svc_lin=svc_lin.predict(X_test)

In [24]:
print(accuracy_score(y_test,y_svc_lin))
print(confusion_matrix(y_test,y_svc_lin))

0.9385964912280702
[[72  2]
 [ 5 35]]


In [25]:
svc_rbf=SVC(kernel='rbf')
svc_rbf.fit(X_train,y_train)
y_svc_rbf=svc_rbf.predict(X_test)

In [26]:
print(accuracy_score(y_test,y_svc_rbf))
print(confusion_matrix(y_test,y_svc_rbf))

0.956140350877193
[[73  1]
 [ 4 36]]


In [27]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(X_train,y_train)
y_dt=dt.predict(X_test)

In [28]:
print(accuracy_score(y_test,y_dt))
print(confusion_matrix(y_test,y_dt))

0.9473684210526315
[[72  2]
 [ 4 36]]


In [29]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(X_train,y_train)
y_rf=rf.predict(X_test)

In [30]:
print(accuracy_score(y_test,y_rf))
print(confusion_matrix(y_test,y_rf))

0.956140350877193
[[73  1]
 [ 4 36]]


In [31]:
from xgboost import XGBClassifier
xgb=XGBClassifier()
xgb.fit(X_train,y_train)
y_xgb=xgb.predict(X_test)

In [32]:
print(accuracy_score(y_test,y_xgb))
print(confusion_matrix(y_test,y_xgb))

0.9649122807017544
[[73  1]
 [ 3 37]]


In [33]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(X_train,y_train)
y_nb=nb.predict(X_test)

In [34]:
print(accuracy_score(y_test,y_nb))
print(confusion_matrix(y_test,y_nb))

0.9298245614035088
[[71  3]
 [ 5 35]]


In [35]:
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
mean_pca=pca.fit_transform(X_mean)

In [36]:
X_se=df[se_attributes]
X_worst=df[worst_attributes]
X_se_train,X_se_test,y_se_train,y_se_test=train_test_split(X_se,y,test_size=0.2,random_state=9)
X_worst_train,X_worst_test,y_worst_train,y_worst_test=train_test_split(X_worst,y,test_size=0.2,random_state=9)
sc_se=StandardScaler()
sc_worst=StandardScaler()
X_se_train=sc_se.fit_transform(X_se_train)
X_se_test=sc_se.transform(X_se_test)
X_worst_train=sc_worst.fit_transform(X_worst_train)
X_worst_test=sc_worst.transform(X_worst_test)

In [37]:
pca_se=PCA(n_components=2)
pca_worst=PCA(n_components=2)
se_pca=pca_se.fit_transform(X_se)
worst_pca=pca_worst.fit_transform(X_worst)

In [41]:
new_df=pd.concat([pd.DataFrame(mean_pca,columns=['pca_1_mean','pca_2_mean']),pd.DataFrame(se_pca,columns=['pca_1_se','pca_2_se']),pd.DataFrame(worst_pca,columns=['pca_1_worst','pca_2_worst']),pd.DataFrame(y,columns=['Diagnosis'])],axis=1)
new_df.head()

pca_1_mean  pca_2_mean    pca_1_se  pca_2_se  pca_1_worst  pca_2_worst  \
0  347.389726   -3.450288  113.204746  0.690344  1140.978986     7.468413   
1  672.360671   -6.224454   33.735343 -1.019933  1076.619259   -11.828989   
2  549.459902    0.291601   53.718366 -0.684875   829.672981    -3.324064   
3 -269.152753    4.105000  -13.070909  0.994878  -312.841940     9.902188   
4  643.562714   -6.209533   54.163589  0.055323   695.842154     1.377358   

   Diagnosis  
0          1  
1          1  
2          1  
3          1  
4          1

In [42]:
new_df.shape

(569, 7)

In [45]:
X=new_df.drop('Diagnosis',axis=1)
y=new_df['Diagnosis']

In [46]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=9)

In [47]:
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import StandardScaler
# from sklearn.linear_model import LogisticRegression
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.svm import SVC
# from sklearn.tree import DecisionTreeClassifier
# from sklearn.ensemble import RandomForestClassifier
# from xgboost import XGBClassifier
# from sklearn.naive_bayes import GaussianNB
# from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# X = new_df.drop('Diagnosis', axis=1)
# y = new_df['Diagnosis']

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=9)

# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

models = {
    'Logistic Regression': LogisticRegression(),
    'K Nearest Neighbors (n=3)': KNeighborsClassifier(n_neighbors=3),
    'K Nearest Neighbors (n=5)': KNeighborsClassifier(n_neighbors=5),
    'Support Vector Classifier (Linear)': SVC(kernel='linear'),
    'Support Vector Classifier (RBF)': SVC(kernel='rbf'),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'XGBoost': XGBClassifier(),
    'Gaussian Naive Bayes': GaussianNB()
}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print(f"--- {name} ---")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
    print("\n")

--- Logistic Regression ---
Accuracy: 0.9298245614035088
Confusion Matrix:
 [[71  3]
 [ 5 35]]


--- K Nearest Neighbors (n=3) ---
Accuracy: 0.9385964912280702
Confusion Matrix:
 [[72  2]
 [ 5 35]]


--- K Nearest Neighbors (n=5) ---
Accuracy: 0.9385964912280702
Confusion Matrix:
 [[72  2]
 [ 5 35]]


--- Support Vector Classifier (Linear) ---
Accuracy: 0.9298245614035088
Confusion Matrix:
 [[72  2]
 [ 6 34]]


--- Support Vector Classifier (RBF) ---
Accuracy: 0.9210526315789473
Confusion Matrix:
 [[74  0]
 [ 9 31]]


--- Decision Tree ---
Accuracy: 0.9210526315789473
Confusion Matrix:
 [[72  2]
 [ 7 33]]


--- Random Forest ---
Accuracy: 0.9298245614035088
Confusion Matrix:
 [[73  1]
 [ 7 33]]


--- XGBoost ---
Accuracy: 0.9298245614035088
Confusion Matrix:
 [[73  1]
 [ 7 33]]


--- Gaussian Naive Bayes ---
Accuracy: 0.8947368421052632
Confusion Matrix:
 [[71  3]
 [ 9 31]]


